# Generated by Django 6.0.3 on 2026-03-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_team_description_team_id_team_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(),
        ),
    ]
