# Generated by Django 6.0.3 on 2026-07-27 03:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0008_project_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=255, null=True)),
                ('current_status', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('month_year', models.CharField(blank=True, max_length=50, null=True)),
                ('stage_percent', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_attachment', models.CharField(blank=True, max_length=255, null=True)),
                ('tds_ded', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('pending_dues', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('pic', models.PositiveIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_by', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_amount_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='project_financials.projectamount')),
            ],
        ),
    ]
