# Generated by Django 6.0.3 on 2026-08-05 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_financials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='type',
            new_name='payment_type',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='project_financials.milestone'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(blank=True, default='Not started', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
