# Generated by Django 6.0.3 on 2026-08-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_financials', '0002_rename_type_paymenthistory_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='invoice_by',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='invoice_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
