# Generated by Django 6.0.3 on 2026-03-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_category_alter_project_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='subcategory',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tab',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
