# Generated by Django 6.0.3 on 2026-04-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_address_alter_client_country_and_more'),
        ('projects', '0006_alter_project_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='clients.client'),
        ),
    ]
