export type CreateLeadResponse = {
  id: number;
  sl_no: number;
  name: string;
  title: string;
  date: string;
  division: string;
  client: string;
  email: string;
  phone: string;
  remarks: string;
  is_deleted: boolean;
  created_at: string;
  updated_at: string;
  lead_status: string;
  lead_source: string;
  last_activity: string | null;
  pic: string;
  is_converted: boolean;
};
