# Generated by Django 6.0.3 on 2026-05-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='project',
        ),
        migrations.RemoveField(
            model_name='works',
            name='team',
        ),
        migrations.AddField(
            model_name='works',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='works',
            name='team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='images',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
