# Generated by Django 6.0.3 on 2026-05-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_remove_works_project_remove_works_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='team_id',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
