# Generated by Django 6.0.3 on 2026-05-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_works_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
