# Generated by Django 6.0.3 on 2026-05-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_alter_works_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='tab',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
