# Generated by Django 6.0.3 on 2026-06-08 04:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('division', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_number', models.CharField(max_length=100, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pic_for_quotation', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='sales/quotations/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='QuotationOne',
        ),
        migrations.DeleteModel(
            name='QuotationThree',
        ),
        migrations.DeleteModel(
            name='QuotationTwo',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='request_for_proposal',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='request_for_sale_quotation',
        ),
        migrations.AddField(
            model_name='proposal',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='sales.lead'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_number',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order_number',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='sales.proposal'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='sales.quotation'),
            preserve_default=False,
        ),
    ]
