# Generated by Django 6.0.3 on 2026-06-08 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_quotation_delete_quotationone_delete_quotationthree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
