# Generated by Django 6.0.3 on 2026-06-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_lead_is_converted_lead_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='pic_for_quotation',
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
