# Generated by Django 6.0.3 on 2026-06-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_quotation_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='versions',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
