# Generated by Django 6.0.3 on 2026-06-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_quotation_quotation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposal_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
