# Generated by Django 6.0.3 on 2026-06-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_proposal_proposal_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='remarks',
        ),
    ]
