# Generated by Django 6.0.3 on 2026-06-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_quotation_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
