# Generated by Django 6.0.3 on 2026-06-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_quotation_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
