# Generated by Django 6.0.3 on 2026-06-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_purchaseorder_purchase_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='team_member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='team_member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='team_member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='team_member_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
