# Generated by Django 6.0.3 on 2026-07-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_lead_team_member_id_proposal_team_member_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_status',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_order_status',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_status',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
    ]
