# Generated by Django 6.0.3 on 2026-07-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_proposal_proposal_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='last_activity',
            new_name='converted_date',
        ),
        migrations.AddField(
            model_name='proposal',
            name='converted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='converted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='converted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
