# Generated by Django 6.0.3 on 2026-07-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_rename_last_activity_lead_converted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
