# Generated by Django 6.0.3 on 2026-07-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_lead_email_alter_lead_pic_alter_proposal_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='attachment',
        ),
        migrations.AddField(
            model_name='quotation',
            name='attachment',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='attachment',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
