# Generated by Django 6.0.3 on 2026-07-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_remove_proposal_attachment_quotation_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='attachment',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
