# Generated by Django 6.0.3 on 2026-07-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_proposal_created_at_proposal_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(blank=True, default='Low', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='priority',
            field=models.CharField(blank=True, default='Low', null=True),
        ),
    ]
