# Generated by Django 6.0.3 on 2026-08-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_lead_priority_proposal_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='probability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
