# Generated by Django 6.0.3 on 2026-08-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_lead_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
